package cn.topdeep.projgroup.entity.db;

import cn.topdeep.projgroup.entity.base.BaseEntity;
import java.util.Date;

public class CodeBuildLog extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_LOG_ID
     *
     * @mbggenerated
     */
    private Integer buildLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_ID
     *
     * @mbggenerated
     */
    private Integer buildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_STATE
     *
     * @mbggenerated
     */
    private Integer buildState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_RESULT
     *
     * @mbggenerated
     */
    private Integer buildResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_MESSAGE
     *
     * @mbggenerated
     */
    private String buildMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_START_TIME
     *
     * @mbggenerated
     */
    private Date buildStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_END_TIME
     *
     * @mbggenerated
     */
    private Date buildEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.BUILD_OPERATOR
     *
     * @mbggenerated
     */
    private String buildOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.PUB0
     *
     * @mbggenerated
     */
    private String pub0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.PUB1
     *
     * @mbggenerated
     */
    private String pub1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.PUB2
     *
     * @mbggenerated
     */
    private String pub2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.PUB3
     *
     * @mbggenerated
     */
    private String pub3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.PUB4
     *
     * @mbggenerated
     */
    private String pub4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_build_log.PUB5
     *
     * @mbggenerated
     */
    private String pub5;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code_build_log
     *
     * @mbggenerated
     */
    public CodeBuildLog(Integer buildLogId, Integer buildId, Integer buildState, Integer buildResult, String buildMessage, Date buildStartTime, Date buildEndTime, String buildOperator, String pub0, String pub1, String pub2, String pub3, String pub4, String pub5) {
        this.buildLogId = buildLogId;
        this.buildId = buildId;
        this.buildState = buildState;
        this.buildResult = buildResult;
        this.buildMessage = buildMessage;
        this.buildStartTime = buildStartTime;
        this.buildEndTime = buildEndTime;
        this.buildOperator = buildOperator;
        this.pub0 = pub0;
        this.pub1 = pub1;
        this.pub2 = pub2;
        this.pub3 = pub3;
        this.pub4 = pub4;
        this.pub5 = pub5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code_build_log
     *
     * @mbggenerated
     */
    public CodeBuildLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_LOG_ID
     *
     * @return the value of t_code_build_log.BUILD_LOG_ID
     *
     * @mbggenerated
     */
    public Integer getBuildLogId() {
        return buildLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_LOG_ID
     *
     * @param buildLogId the value for t_code_build_log.BUILD_LOG_ID
     *
     * @mbggenerated
     */
    public void setBuildLogId(Integer buildLogId) {
        this.buildLogId = buildLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_ID
     *
     * @return the value of t_code_build_log.BUILD_ID
     *
     * @mbggenerated
     */
    public Integer getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_ID
     *
     * @param buildId the value for t_code_build_log.BUILD_ID
     *
     * @mbggenerated
     */
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_STATE
     *
     * @return the value of t_code_build_log.BUILD_STATE
     *
     * @mbggenerated
     */
    public Integer getBuildState() {
        return buildState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_STATE
     *
     * @param buildState the value for t_code_build_log.BUILD_STATE
     *
     * @mbggenerated
     */
    public void setBuildState(Integer buildState) {
        this.buildState = buildState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_RESULT
     *
     * @return the value of t_code_build_log.BUILD_RESULT
     *
     * @mbggenerated
     */
    public Integer getBuildResult() {
        return buildResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_RESULT
     *
     * @param buildResult the value for t_code_build_log.BUILD_RESULT
     *
     * @mbggenerated
     */
    public void setBuildResult(Integer buildResult) {
        this.buildResult = buildResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_MESSAGE
     *
     * @return the value of t_code_build_log.BUILD_MESSAGE
     *
     * @mbggenerated
     */
    public String getBuildMessage() {
        return buildMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_MESSAGE
     *
     * @param buildMessage the value for t_code_build_log.BUILD_MESSAGE
     *
     * @mbggenerated
     */
    public void setBuildMessage(String buildMessage) {
        this.buildMessage = buildMessage == null ? null : buildMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_START_TIME
     *
     * @return the value of t_code_build_log.BUILD_START_TIME
     *
     * @mbggenerated
     */
    public Date getBuildStartTime() {
        return buildStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_START_TIME
     *
     * @param buildStartTime the value for t_code_build_log.BUILD_START_TIME
     *
     * @mbggenerated
     */
    public void setBuildStartTime(Date buildStartTime) {
        this.buildStartTime = buildStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_END_TIME
     *
     * @return the value of t_code_build_log.BUILD_END_TIME
     *
     * @mbggenerated
     */
    public Date getBuildEndTime() {
        return buildEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_END_TIME
     *
     * @param buildEndTime the value for t_code_build_log.BUILD_END_TIME
     *
     * @mbggenerated
     */
    public void setBuildEndTime(Date buildEndTime) {
        this.buildEndTime = buildEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.BUILD_OPERATOR
     *
     * @return the value of t_code_build_log.BUILD_OPERATOR
     *
     * @mbggenerated
     */
    public String getBuildOperator() {
        return buildOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.BUILD_OPERATOR
     *
     * @param buildOperator the value for t_code_build_log.BUILD_OPERATOR
     *
     * @mbggenerated
     */
    public void setBuildOperator(String buildOperator) {
        this.buildOperator = buildOperator == null ? null : buildOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.PUB0
     *
     * @return the value of t_code_build_log.PUB0
     *
     * @mbggenerated
     */
    public String getPub0() {
        return pub0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.PUB0
     *
     * @param pub0 the value for t_code_build_log.PUB0
     *
     * @mbggenerated
     */
    public void setPub0(String pub0) {
        this.pub0 = pub0 == null ? null : pub0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.PUB1
     *
     * @return the value of t_code_build_log.PUB1
     *
     * @mbggenerated
     */
    public String getPub1() {
        return pub1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.PUB1
     *
     * @param pub1 the value for t_code_build_log.PUB1
     *
     * @mbggenerated
     */
    public void setPub1(String pub1) {
        this.pub1 = pub1 == null ? null : pub1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.PUB2
     *
     * @return the value of t_code_build_log.PUB2
     *
     * @mbggenerated
     */
    public String getPub2() {
        return pub2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.PUB2
     *
     * @param pub2 the value for t_code_build_log.PUB2
     *
     * @mbggenerated
     */
    public void setPub2(String pub2) {
        this.pub2 = pub2 == null ? null : pub2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.PUB3
     *
     * @return the value of t_code_build_log.PUB3
     *
     * @mbggenerated
     */
    public String getPub3() {
        return pub3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.PUB3
     *
     * @param pub3 the value for t_code_build_log.PUB3
     *
     * @mbggenerated
     */
    public void setPub3(String pub3) {
        this.pub3 = pub3 == null ? null : pub3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.PUB4
     *
     * @return the value of t_code_build_log.PUB4
     *
     * @mbggenerated
     */
    public String getPub4() {
        return pub4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.PUB4
     *
     * @param pub4 the value for t_code_build_log.PUB4
     *
     * @mbggenerated
     */
    public void setPub4(String pub4) {
        this.pub4 = pub4 == null ? null : pub4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_build_log.PUB5
     *
     * @return the value of t_code_build_log.PUB5
     *
     * @mbggenerated
     */
    public String getPub5() {
        return pub5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_build_log.PUB5
     *
     * @param pub5 the value for t_code_build_log.PUB5
     *
     * @mbggenerated
     */
    public void setPub5(String pub5) {
        this.pub5 = pub5 == null ? null : pub5.trim();
    }
}