package cn.topdeep.projgroup.entity.db;

import cn.topdeep.projgroup.entity.db.FuncTest;
import cn.topdeep.projgroup.entity.db.FuncTestExample;
import cn.topdeep.projgroup.entity.db.FuncTestKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FuncTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int countByExample(FuncTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int deleteByExample(FuncTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FuncTestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int insert(FuncTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int insertSelective(FuncTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    List<FuncTest> selectByExample(FuncTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    FuncTest selectByPrimaryKey(FuncTestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FuncTest record, @Param("example") FuncTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FuncTest record, @Param("example") FuncTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FuncTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FuncTest record);
}