package cn.topdeep.projgroup.entity.db;

import cn.topdeep.projgroup.entity.db.ProjectJoinUserExample;
import cn.topdeep.projgroup.entity.db.ProjectJoinUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectJoinUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    int countByExample(ProjectJoinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectJoinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ProjectJoinUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    int insert(ProjectJoinUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    int insertSelective(ProjectJoinUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    List<ProjectJoinUserKey> selectByExample(ProjectJoinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectJoinUserKey record, @Param("example") ProjectJoinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_join_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectJoinUserKey record, @Param("example") ProjectJoinUserExample example);
}