package cn.topdeep.projgroup.entity.db;

import common.entity.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressIsNull() {
            addCriterion("LAST_LOGIN_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressIsNotNull() {
            addCriterion("LAST_LOGIN_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressEqualTo(String value) {
            addCriterion("LAST_LOGIN_ADDRESS =", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressNotEqualTo(String value) {
            addCriterion("LAST_LOGIN_ADDRESS <>", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressGreaterThan(String value) {
            addCriterion("LAST_LOGIN_ADDRESS >", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_LOGIN_ADDRESS >=", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressLessThan(String value) {
            addCriterion("LAST_LOGIN_ADDRESS <", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressLessThanOrEqualTo(String value) {
            addCriterion("LAST_LOGIN_ADDRESS <=", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressLike(String value) {
            addCriterion("LAST_LOGIN_ADDRESS like", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressNotLike(String value) {
            addCriterion("LAST_LOGIN_ADDRESS not like", value, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressIn(List<String> values) {
            addCriterion("LAST_LOGIN_ADDRESS in", values, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressNotIn(List<String> values) {
            addCriterion("LAST_LOGIN_ADDRESS not in", values, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressBetween(String value1, String value2) {
            addCriterion("LAST_LOGIN_ADDRESS between", value1, value2, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginAddressNotBetween(String value1, String value2) {
            addCriterion("LAST_LOGIN_ADDRESS not between", value1, value2, "lastLoginAddress");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("LAST_LOGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("LAST_LOGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("LAST_LOGIN_TIME >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("LAST_LOGIN_TIME <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("LAST_LOGIN_TIME in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("LAST_LOGIN_TIME not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_LOGIN_TIME between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_LOGIN_TIME not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLoginCountIsNull() {
            addCriterion("LOGIN_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andLoginCountIsNotNull() {
            addCriterion("LOGIN_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andLoginCountEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT =", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT <>", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountGreaterThan(Integer value) {
            addCriterion("LOGIN_COUNT >", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT >=", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountLessThan(Integer value) {
            addCriterion("LOGIN_COUNT <", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountLessThanOrEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT <=", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountIn(List<Integer> values) {
            addCriterion("LOGIN_COUNT in", values, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotIn(List<Integer> values) {
            addCriterion("LOGIN_COUNT not in", values, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountBetween(Integer value1, Integer value2) {
            addCriterion("LOGIN_COUNT between", value1, value2, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotBetween(Integer value1, Integer value2) {
            addCriterion("LOGIN_COUNT not between", value1, value2, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("LOGIN_NAME =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("LOGIN_NAME <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("LOGIN_NAME >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("LOGIN_NAME <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("LOGIN_NAME like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("LOGIN_NAME not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("LOGIN_NAME in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("LOGIN_NAME not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginPassIsNull() {
            addCriterion("LOGIN_PASS is null");
            return (Criteria) this;
        }

        public Criteria andLoginPassIsNotNull() {
            addCriterion("LOGIN_PASS is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPassEqualTo(String value) {
            addCriterion("LOGIN_PASS =", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassNotEqualTo(String value) {
            addCriterion("LOGIN_PASS <>", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassGreaterThan(String value) {
            addCriterion("LOGIN_PASS >", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_PASS >=", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassLessThan(String value) {
            addCriterion("LOGIN_PASS <", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_PASS <=", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassLike(String value) {
            addCriterion("LOGIN_PASS like", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassNotLike(String value) {
            addCriterion("LOGIN_PASS not like", value, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassIn(List<String> values) {
            addCriterion("LOGIN_PASS in", values, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassNotIn(List<String> values) {
            addCriterion("LOGIN_PASS not in", values, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassBetween(String value1, String value2) {
            addCriterion("LOGIN_PASS between", value1, value2, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassNotBetween(String value1, String value2) {
            addCriterion("LOGIN_PASS not between", value1, value2, "loginPass");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("REAL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("REAL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("REAL_NAME =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("REAL_NAME <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("REAL_NAME >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("REAL_NAME >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("REAL_NAME <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("REAL_NAME <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("REAL_NAME like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("REAL_NAME not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("REAL_NAME in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("REAL_NAME not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("REAL_NAME between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("REAL_NAME not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("USER_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("USER_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("USER_EMAIL =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("USER_EMAIL <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("USER_EMAIL >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("USER_EMAIL <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("USER_EMAIL like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("USER_EMAIL not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("USER_EMAIL in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("USER_EMAIL not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("USER_EMAIL between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("USER_EMAIL not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserMemoIsNull() {
            addCriterion("USER_MEMO is null");
            return (Criteria) this;
        }

        public Criteria andUserMemoIsNotNull() {
            addCriterion("USER_MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andUserMemoEqualTo(String value) {
            addCriterion("USER_MEMO =", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoNotEqualTo(String value) {
            addCriterion("USER_MEMO <>", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoGreaterThan(String value) {
            addCriterion("USER_MEMO >", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoGreaterThanOrEqualTo(String value) {
            addCriterion("USER_MEMO >=", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoLessThan(String value) {
            addCriterion("USER_MEMO <", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoLessThanOrEqualTo(String value) {
            addCriterion("USER_MEMO <=", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoLike(String value) {
            addCriterion("USER_MEMO like", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoNotLike(String value) {
            addCriterion("USER_MEMO not like", value, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoIn(List<String> values) {
            addCriterion("USER_MEMO in", values, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoNotIn(List<String> values) {
            addCriterion("USER_MEMO not in", values, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoBetween(String value1, String value2) {
            addCriterion("USER_MEMO between", value1, value2, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMemoNotBetween(String value1, String value2) {
            addCriterion("USER_MEMO not between", value1, value2, "userMemo");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNull() {
            addCriterion("USER_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNotNull() {
            addCriterion("USER_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andUserMobileEqualTo(String value) {
            addCriterion("USER_MOBILE =", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotEqualTo(String value) {
            addCriterion("USER_MOBILE <>", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThan(String value) {
            addCriterion("USER_MOBILE >", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThanOrEqualTo(String value) {
            addCriterion("USER_MOBILE >=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThan(String value) {
            addCriterion("USER_MOBILE <", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThanOrEqualTo(String value) {
            addCriterion("USER_MOBILE <=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLike(String value) {
            addCriterion("USER_MOBILE like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotLike(String value) {
            addCriterion("USER_MOBILE not like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileIn(List<String> values) {
            addCriterion("USER_MOBILE in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotIn(List<String> values) {
            addCriterion("USER_MOBILE not in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileBetween(String value1, String value2) {
            addCriterion("USER_MOBILE between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotBetween(String value1, String value2) {
            addCriterion("USER_MOBILE not between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMsnIsNull() {
            addCriterion("USER_MSN is null");
            return (Criteria) this;
        }

        public Criteria andUserMsnIsNotNull() {
            addCriterion("USER_MSN is not null");
            return (Criteria) this;
        }

        public Criteria andUserMsnEqualTo(String value) {
            addCriterion("USER_MSN =", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnNotEqualTo(String value) {
            addCriterion("USER_MSN <>", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnGreaterThan(String value) {
            addCriterion("USER_MSN >", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnGreaterThanOrEqualTo(String value) {
            addCriterion("USER_MSN >=", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnLessThan(String value) {
            addCriterion("USER_MSN <", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnLessThanOrEqualTo(String value) {
            addCriterion("USER_MSN <=", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnLike(String value) {
            addCriterion("USER_MSN like", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnNotLike(String value) {
            addCriterion("USER_MSN not like", value, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnIn(List<String> values) {
            addCriterion("USER_MSN in", values, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnNotIn(List<String> values) {
            addCriterion("USER_MSN not in", values, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnBetween(String value1, String value2) {
            addCriterion("USER_MSN between", value1, value2, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserMsnNotBetween(String value1, String value2) {
            addCriterion("USER_MSN not between", value1, value2, "userMsn");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesIsNull() {
            addCriterion("USER_PRIVILEGES is null");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesIsNotNull() {
            addCriterion("USER_PRIVILEGES is not null");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesEqualTo(String value) {
            addCriterion("USER_PRIVILEGES =", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesNotEqualTo(String value) {
            addCriterion("USER_PRIVILEGES <>", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesGreaterThan(String value) {
            addCriterion("USER_PRIVILEGES >", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PRIVILEGES >=", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesLessThan(String value) {
            addCriterion("USER_PRIVILEGES <", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesLessThanOrEqualTo(String value) {
            addCriterion("USER_PRIVILEGES <=", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesLike(String value) {
            addCriterion("USER_PRIVILEGES like", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesNotLike(String value) {
            addCriterion("USER_PRIVILEGES not like", value, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesIn(List<String> values) {
            addCriterion("USER_PRIVILEGES in", values, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesNotIn(List<String> values) {
            addCriterion("USER_PRIVILEGES not in", values, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesBetween(String value1, String value2) {
            addCriterion("USER_PRIVILEGES between", value1, value2, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserPrivilegesNotBetween(String value1, String value2) {
            addCriterion("USER_PRIVILEGES not between", value1, value2, "userPrivileges");
            return (Criteria) this;
        }

        public Criteria andUserQqIsNull() {
            addCriterion("USER_QQ is null");
            return (Criteria) this;
        }

        public Criteria andUserQqIsNotNull() {
            addCriterion("USER_QQ is not null");
            return (Criteria) this;
        }

        public Criteria andUserQqEqualTo(String value) {
            addCriterion("USER_QQ =", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqNotEqualTo(String value) {
            addCriterion("USER_QQ <>", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqGreaterThan(String value) {
            addCriterion("USER_QQ >", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqGreaterThanOrEqualTo(String value) {
            addCriterion("USER_QQ >=", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqLessThan(String value) {
            addCriterion("USER_QQ <", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqLessThanOrEqualTo(String value) {
            addCriterion("USER_QQ <=", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqLike(String value) {
            addCriterion("USER_QQ like", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqNotLike(String value) {
            addCriterion("USER_QQ not like", value, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqIn(List<String> values) {
            addCriterion("USER_QQ in", values, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqNotIn(List<String> values) {
            addCriterion("USER_QQ not in", values, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqBetween(String value1, String value2) {
            addCriterion("USER_QQ between", value1, value2, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserQqNotBetween(String value1, String value2) {
            addCriterion("USER_QQ not between", value1, value2, "userQq");
            return (Criteria) this;
        }

        public Criteria andUserRolesIsNull() {
            addCriterion("USER_ROLES is null");
            return (Criteria) this;
        }

        public Criteria andUserRolesIsNotNull() {
            addCriterion("USER_ROLES is not null");
            return (Criteria) this;
        }

        public Criteria andUserRolesEqualTo(String value) {
            addCriterion("USER_ROLES =", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesNotEqualTo(String value) {
            addCriterion("USER_ROLES <>", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesGreaterThan(String value) {
            addCriterion("USER_ROLES >", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ROLES >=", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesLessThan(String value) {
            addCriterion("USER_ROLES <", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesLessThanOrEqualTo(String value) {
            addCriterion("USER_ROLES <=", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesLike(String value) {
            addCriterion("USER_ROLES like", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesNotLike(String value) {
            addCriterion("USER_ROLES not like", value, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesIn(List<String> values) {
            addCriterion("USER_ROLES in", values, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesNotIn(List<String> values) {
            addCriterion("USER_ROLES not in", values, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesBetween(String value1, String value2) {
            addCriterion("USER_ROLES between", value1, value2, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserRolesNotBetween(String value1, String value2) {
            addCriterion("USER_ROLES not between", value1, value2, "userRoles");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNull() {
            addCriterion("USER_STATE is null");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNotNull() {
            addCriterion("USER_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andUserStateEqualTo(Integer value) {
            addCriterion("USER_STATE =", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotEqualTo(Integer value) {
            addCriterion("USER_STATE <>", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThan(Integer value) {
            addCriterion("USER_STATE >", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_STATE >=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThan(Integer value) {
            addCriterion("USER_STATE <", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThanOrEqualTo(Integer value) {
            addCriterion("USER_STATE <=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateIn(List<Integer> values) {
            addCriterion("USER_STATE in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotIn(List<Integer> values) {
            addCriterion("USER_STATE not in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateBetween(Integer value1, Integer value2) {
            addCriterion("USER_STATE between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_STATE not between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneIsNull() {
            addCriterion("USER_TELEPHONE is null");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneIsNotNull() {
            addCriterion("USER_TELEPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneEqualTo(String value) {
            addCriterion("USER_TELEPHONE =", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneNotEqualTo(String value) {
            addCriterion("USER_TELEPHONE <>", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneGreaterThan(String value) {
            addCriterion("USER_TELEPHONE >", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TELEPHONE >=", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneLessThan(String value) {
            addCriterion("USER_TELEPHONE <", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneLessThanOrEqualTo(String value) {
            addCriterion("USER_TELEPHONE <=", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneLike(String value) {
            addCriterion("USER_TELEPHONE like", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneNotLike(String value) {
            addCriterion("USER_TELEPHONE not like", value, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneIn(List<String> values) {
            addCriterion("USER_TELEPHONE in", values, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneNotIn(List<String> values) {
            addCriterion("USER_TELEPHONE not in", values, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneBetween(String value1, String value2) {
            addCriterion("USER_TELEPHONE between", value1, value2, "userTelephone");
            return (Criteria) this;
        }

        public Criteria andUserTelephoneNotBetween(String value1, String value2) {
            addCriterion("USER_TELEPHONE not between", value1, value2, "userTelephone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}