package cn.topdeep.projgroup.entity.db;

import cn.topdeep.projgroup.entity.base.BaseEntity;
import java.util.Date;

public class VWorkLogView extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_work_log_view.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_work_log_view.work_day
     *
     * @mbggenerated
     */
    private Date workDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_work_log_view.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_work_log_view
     *
     * @mbggenerated
     */
    public VWorkLogView(String realName, Date workDay, Date modifyTime) {
        this.realName = realName;
        this.workDay = workDay;
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_work_log_view
     *
     * @mbggenerated
     */
    public VWorkLogView() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_work_log_view.real_name
     *
     * @return the value of v_work_log_view.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_work_log_view.real_name
     *
     * @param realName the value for v_work_log_view.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_work_log_view.work_day
     *
     * @return the value of v_work_log_view.work_day
     *
     * @mbggenerated
     */
    public Date getWorkDay() {
        return workDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_work_log_view.work_day
     *
     * @param workDay the value for v_work_log_view.work_day
     *
     * @mbggenerated
     */
    public void setWorkDay(Date workDay) {
        this.workDay = workDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_work_log_view.modify_time
     *
     * @return the value of v_work_log_view.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_work_log_view.modify_time
     *
     * @param modifyTime the value for v_work_log_view.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}