package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Ao563aeeActivityEntity;
import cn.topdeep.projgroup.entity.jiradb.Ao563aeeActivityEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ao563aeeActivityEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int countByExample(Ao563aeeActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int deleteByExample(Ao563aeeActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int insert(Ao563aeeActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int insertSelective(Ao563aeeActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    List<Ao563aeeActivityEntity> selectByExampleWithBLOBs(Ao563aeeActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    List<Ao563aeeActivityEntity> selectByExample(Ao563aeeActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    Ao563aeeActivityEntity selectByPrimaryKey(Long activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Ao563aeeActivityEntity record, @Param("example") Ao563aeeActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Ao563aeeActivityEntity record, @Param("example") Ao563aeeActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Ao563aeeActivityEntity record, @Param("example") Ao563aeeActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ao563aeeActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Ao563aeeActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ao563aeeActivityEntity record);
}