package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Ao563aeeMediaLinkEntity;
import cn.topdeep.projgroup.entity.jiradb.Ao563aeeMediaLinkEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ao563aeeMediaLinkEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int countByExample(Ao563aeeMediaLinkEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int deleteByExample(Ao563aeeMediaLinkEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int insert(Ao563aeeMediaLinkEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int insertSelective(Ao563aeeMediaLinkEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    List<Ao563aeeMediaLinkEntity> selectByExample(Ao563aeeMediaLinkEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    Ao563aeeMediaLinkEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Ao563aeeMediaLinkEntity record, @Param("example") Ao563aeeMediaLinkEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Ao563aeeMediaLinkEntity record, @Param("example") Ao563aeeMediaLinkEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ao563aeeMediaLinkEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_media_link_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ao563aeeMediaLinkEntity record);
}