package cn.topdeep.projgroup.entity.jiradb;

import common.entity.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Ao563aeeActivityEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public Ao563aeeActivityEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("ACTIVITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("ACTIVITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andActivityIdEqualTo(Long value) {
            addCriterion("ACTIVITY_ID =", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotEqualTo(Long value) {
            addCriterion("ACTIVITY_ID <>", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThan(Long value) {
            addCriterion("ACTIVITY_ID >", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ACTIVITY_ID >=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThan(Long value) {
            addCriterion("ACTIVITY_ID <", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(Long value) {
            addCriterion("ACTIVITY_ID <=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIn(List<Long> values) {
            addCriterion("ACTIVITY_ID in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotIn(List<Long> values) {
            addCriterion("ACTIVITY_ID not in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdBetween(Long value1, Long value2) {
            addCriterion("ACTIVITY_ID between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotBetween(Long value1, Long value2) {
            addCriterion("ACTIVITY_ID not between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActorIdIsNull() {
            addCriterion("ACTOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andActorIdIsNotNull() {
            addCriterion("ACTOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andActorIdEqualTo(Integer value) {
            addCriterion("ACTOR_ID =", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdNotEqualTo(Integer value) {
            addCriterion("ACTOR_ID <>", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdGreaterThan(Integer value) {
            addCriterion("ACTOR_ID >", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTOR_ID >=", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdLessThan(Integer value) {
            addCriterion("ACTOR_ID <", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACTOR_ID <=", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdIn(List<Integer> values) {
            addCriterion("ACTOR_ID in", values, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdNotIn(List<Integer> values) {
            addCriterion("ACTOR_ID not in", values, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdBetween(Integer value1, Integer value2) {
            addCriterion("ACTOR_ID between", value1, value2, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTOR_ID not between", value1, value2, "actorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameIsNull() {
            addCriterion("GENERATOR_DISPLAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameIsNotNull() {
            addCriterion("GENERATOR_DISPLAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameEqualTo(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME =", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameNotEqualTo(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME <>", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameGreaterThan(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME >", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME >=", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameLessThan(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME <", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME <=", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameLike(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME like", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameNotLike(String value) {
            addCriterion("GENERATOR_DISPLAY_NAME not like", value, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameIn(List<String> values) {
            addCriterion("GENERATOR_DISPLAY_NAME in", values, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameNotIn(List<String> values) {
            addCriterion("GENERATOR_DISPLAY_NAME not in", values, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameBetween(String value1, String value2) {
            addCriterion("GENERATOR_DISPLAY_NAME between", value1, value2, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorDisplayNameNotBetween(String value1, String value2) {
            addCriterion("GENERATOR_DISPLAY_NAME not between", value1, value2, "generatorDisplayName");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdIsNull() {
            addCriterion("GENERATOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdIsNotNull() {
            addCriterion("GENERATOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdEqualTo(String value) {
            addCriterion("GENERATOR_ID =", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdNotEqualTo(String value) {
            addCriterion("GENERATOR_ID <>", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdGreaterThan(String value) {
            addCriterion("GENERATOR_ID >", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdGreaterThanOrEqualTo(String value) {
            addCriterion("GENERATOR_ID >=", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdLessThan(String value) {
            addCriterion("GENERATOR_ID <", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdLessThanOrEqualTo(String value) {
            addCriterion("GENERATOR_ID <=", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdLike(String value) {
            addCriterion("GENERATOR_ID like", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdNotLike(String value) {
            addCriterion("GENERATOR_ID not like", value, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdIn(List<String> values) {
            addCriterion("GENERATOR_ID in", values, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdNotIn(List<String> values) {
            addCriterion("GENERATOR_ID not in", values, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdBetween(String value1, String value2) {
            addCriterion("GENERATOR_ID between", value1, value2, "generatorId");
            return (Criteria) this;
        }

        public Criteria andGeneratorIdNotBetween(String value1, String value2) {
            addCriterion("GENERATOR_ID not between", value1, value2, "generatorId");
            return (Criteria) this;
        }

        public Criteria andIconIdIsNull() {
            addCriterion("ICON_ID is null");
            return (Criteria) this;
        }

        public Criteria andIconIdIsNotNull() {
            addCriterion("ICON_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIconIdEqualTo(Integer value) {
            addCriterion("ICON_ID =", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdNotEqualTo(Integer value) {
            addCriterion("ICON_ID <>", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdGreaterThan(Integer value) {
            addCriterion("ICON_ID >", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ICON_ID >=", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdLessThan(Integer value) {
            addCriterion("ICON_ID <", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdLessThanOrEqualTo(Integer value) {
            addCriterion("ICON_ID <=", value, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdIn(List<Integer> values) {
            addCriterion("ICON_ID in", values, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdNotIn(List<Integer> values) {
            addCriterion("ICON_ID not in", values, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdBetween(Integer value1, Integer value2) {
            addCriterion("ICON_ID between", value1, value2, "iconId");
            return (Criteria) this;
        }

        public Criteria andIconIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ICON_ID not between", value1, value2, "iconId");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIssueKeyIsNull() {
            addCriterion("ISSUE_KEY is null");
            return (Criteria) this;
        }

        public Criteria andIssueKeyIsNotNull() {
            addCriterion("ISSUE_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andIssueKeyEqualTo(String value) {
            addCriterion("ISSUE_KEY =", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyNotEqualTo(String value) {
            addCriterion("ISSUE_KEY <>", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyGreaterThan(String value) {
            addCriterion("ISSUE_KEY >", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUE_KEY >=", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyLessThan(String value) {
            addCriterion("ISSUE_KEY <", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyLessThanOrEqualTo(String value) {
            addCriterion("ISSUE_KEY <=", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyLike(String value) {
            addCriterion("ISSUE_KEY like", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyNotLike(String value) {
            addCriterion("ISSUE_KEY not like", value, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyIn(List<String> values) {
            addCriterion("ISSUE_KEY in", values, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyNotIn(List<String> values) {
            addCriterion("ISSUE_KEY not in", values, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyBetween(String value1, String value2) {
            addCriterion("ISSUE_KEY between", value1, value2, "issueKey");
            return (Criteria) this;
        }

        public Criteria andIssueKeyNotBetween(String value1, String value2) {
            addCriterion("ISSUE_KEY not between", value1, value2, "issueKey");
            return (Criteria) this;
        }

        public Criteria andObjectIdIsNull() {
            addCriterion("OBJECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andObjectIdIsNotNull() {
            addCriterion("OBJECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andObjectIdEqualTo(Integer value) {
            addCriterion("OBJECT_ID =", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotEqualTo(Integer value) {
            addCriterion("OBJECT_ID <>", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdGreaterThan(Integer value) {
            addCriterion("OBJECT_ID >", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("OBJECT_ID >=", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLessThan(Integer value) {
            addCriterion("OBJECT_ID <", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("OBJECT_ID <=", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdIn(List<Integer> values) {
            addCriterion("OBJECT_ID in", values, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotIn(List<Integer> values) {
            addCriterion("OBJECT_ID not in", values, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdBetween(Integer value1, Integer value2) {
            addCriterion("OBJECT_ID between", value1, value2, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("OBJECT_ID not between", value1, value2, "objectId");
            return (Criteria) this;
        }

        public Criteria andPosterIsNull() {
            addCriterion("POSTER is null");
            return (Criteria) this;
        }

        public Criteria andPosterIsNotNull() {
            addCriterion("POSTER is not null");
            return (Criteria) this;
        }

        public Criteria andPosterEqualTo(String value) {
            addCriterion("POSTER =", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotEqualTo(String value) {
            addCriterion("POSTER <>", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterGreaterThan(String value) {
            addCriterion("POSTER >", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterGreaterThanOrEqualTo(String value) {
            addCriterion("POSTER >=", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterLessThan(String value) {
            addCriterion("POSTER <", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterLessThanOrEqualTo(String value) {
            addCriterion("POSTER <=", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterLike(String value) {
            addCriterion("POSTER like", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotLike(String value) {
            addCriterion("POSTER not like", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterIn(List<String> values) {
            addCriterion("POSTER in", values, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotIn(List<String> values) {
            addCriterion("POSTER not in", values, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterBetween(String value1, String value2) {
            addCriterion("POSTER between", value1, value2, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotBetween(String value1, String value2) {
            addCriterion("POSTER not between", value1, value2, "poster");
            return (Criteria) this;
        }

        public Criteria andProjectKeyIsNull() {
            addCriterion("PROJECT_KEY is null");
            return (Criteria) this;
        }

        public Criteria andProjectKeyIsNotNull() {
            addCriterion("PROJECT_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andProjectKeyEqualTo(String value) {
            addCriterion("PROJECT_KEY =", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotEqualTo(String value) {
            addCriterion("PROJECT_KEY <>", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyGreaterThan(String value) {
            addCriterion("PROJECT_KEY >", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_KEY >=", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyLessThan(String value) {
            addCriterion("PROJECT_KEY <", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_KEY <=", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyLike(String value) {
            addCriterion("PROJECT_KEY like", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotLike(String value) {
            addCriterion("PROJECT_KEY not like", value, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyIn(List<String> values) {
            addCriterion("PROJECT_KEY in", values, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotIn(List<String> values) {
            addCriterion("PROJECT_KEY not in", values, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyBetween(String value1, String value2) {
            addCriterion("PROJECT_KEY between", value1, value2, "projectKey");
            return (Criteria) this;
        }

        public Criteria andProjectKeyNotBetween(String value1, String value2) {
            addCriterion("PROJECT_KEY not between", value1, value2, "projectKey");
            return (Criteria) this;
        }

        public Criteria andPublishedIsNull() {
            addCriterion("PUBLISHED is null");
            return (Criteria) this;
        }

        public Criteria andPublishedIsNotNull() {
            addCriterion("PUBLISHED is not null");
            return (Criteria) this;
        }

        public Criteria andPublishedEqualTo(Date value) {
            addCriterion("PUBLISHED =", value, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedNotEqualTo(Date value) {
            addCriterion("PUBLISHED <>", value, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedGreaterThan(Date value) {
            addCriterion("PUBLISHED >", value, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedGreaterThanOrEqualTo(Date value) {
            addCriterion("PUBLISHED >=", value, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedLessThan(Date value) {
            addCriterion("PUBLISHED <", value, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedLessThanOrEqualTo(Date value) {
            addCriterion("PUBLISHED <=", value, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedIn(List<Date> values) {
            addCriterion("PUBLISHED in", values, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedNotIn(List<Date> values) {
            addCriterion("PUBLISHED not in", values, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedBetween(Date value1, Date value2) {
            addCriterion("PUBLISHED between", value1, value2, "published");
            return (Criteria) this;
        }

        public Criteria andPublishedNotBetween(Date value1, Date value2) {
            addCriterion("PUBLISHED not between", value1, value2, "published");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNull() {
            addCriterion("TARGET_ID is null");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNotNull() {
            addCriterion("TARGET_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTargetIdEqualTo(Integer value) {
            addCriterion("TARGET_ID =", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotEqualTo(Integer value) {
            addCriterion("TARGET_ID <>", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThan(Integer value) {
            addCriterion("TARGET_ID >", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TARGET_ID >=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThan(Integer value) {
            addCriterion("TARGET_ID <", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThanOrEqualTo(Integer value) {
            addCriterion("TARGET_ID <=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIn(List<Integer> values) {
            addCriterion("TARGET_ID in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotIn(List<Integer> values) {
            addCriterion("TARGET_ID not in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdBetween(Integer value1, Integer value2) {
            addCriterion("TARGET_ID between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TARGET_ID not between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andVerbIsNull() {
            addCriterion("VERB is null");
            return (Criteria) this;
        }

        public Criteria andVerbIsNotNull() {
            addCriterion("VERB is not null");
            return (Criteria) this;
        }

        public Criteria andVerbEqualTo(String value) {
            addCriterion("VERB =", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbNotEqualTo(String value) {
            addCriterion("VERB <>", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbGreaterThan(String value) {
            addCriterion("VERB >", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbGreaterThanOrEqualTo(String value) {
            addCriterion("VERB >=", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbLessThan(String value) {
            addCriterion("VERB <", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbLessThanOrEqualTo(String value) {
            addCriterion("VERB <=", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbLike(String value) {
            addCriterion("VERB like", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbNotLike(String value) {
            addCriterion("VERB not like", value, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbIn(List<String> values) {
            addCriterion("VERB in", values, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbNotIn(List<String> values) {
            addCriterion("VERB not in", values, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbBetween(String value1, String value2) {
            addCriterion("VERB between", value1, value2, "verb");
            return (Criteria) this;
        }

        public Criteria andVerbNotBetween(String value1, String value2) {
            addCriterion("VERB not between", value1, value2, "verb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ao_563aee_activity_entity
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}