package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Ao854ed6StartDate;
import cn.topdeep.projgroup.entity.jiradb.Ao854ed6StartDateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ao854ed6StartDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int countByExample(Ao854ed6StartDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int deleteByExample(Ao854ed6StartDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int insert(Ao854ed6StartDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int insertSelective(Ao854ed6StartDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    List<Ao854ed6StartDate> selectByExample(Ao854ed6StartDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    Ao854ed6StartDate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Ao854ed6StartDate record, @Param("example") Ao854ed6StartDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Ao854ed6StartDate record, @Param("example") Ao854ed6StartDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ao854ed6StartDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_854ed6_start_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ao854ed6StartDate record);
}