package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.AoD5e466Configuration;
import cn.topdeep.projgroup.entity.jiradb.AoD5e466ConfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AoD5e466ConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int countByExample(AoD5e466ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int deleteByExample(AoD5e466ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int insert(AoD5e466Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int insertSelective(AoD5e466Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    List<AoD5e466Configuration> selectByExample(AoD5e466ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    AoD5e466Configuration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AoD5e466Configuration record, @Param("example") AoD5e466ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AoD5e466Configuration record, @Param("example") AoD5e466ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AoD5e466Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AoD5e466Configuration record);
}