package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;

public class AoD5e466Element extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ao_d5e466_element.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ao_d5e466_element.ELEMENTTYPE
     *
     * @mbggenerated
     */
    private String elementtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ao_d5e466_element.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ao_d5e466_element.PRIORITY
     *
     * @mbggenerated
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_element
     *
     * @mbggenerated
     */
    public AoD5e466Element(Integer id, String elementtype, String name, Integer priority) {
        this.id = id;
        this.elementtype = elementtype;
        this.name = name;
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_element
     *
     * @mbggenerated
     */
    public AoD5e466Element() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ao_d5e466_element.ID
     *
     * @return the value of ao_d5e466_element.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ao_d5e466_element.ID
     *
     * @param id the value for ao_d5e466_element.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ao_d5e466_element.ELEMENTTYPE
     *
     * @return the value of ao_d5e466_element.ELEMENTTYPE
     *
     * @mbggenerated
     */
    public String getElementtype() {
        return elementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ao_d5e466_element.ELEMENTTYPE
     *
     * @param elementtype the value for ao_d5e466_element.ELEMENTTYPE
     *
     * @mbggenerated
     */
    public void setElementtype(String elementtype) {
        this.elementtype = elementtype == null ? null : elementtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ao_d5e466_element.NAME
     *
     * @return the value of ao_d5e466_element.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ao_d5e466_element.NAME
     *
     * @param name the value for ao_d5e466_element.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ao_d5e466_element.PRIORITY
     *
     * @return the value of ao_d5e466_element.PRIORITY
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ao_d5e466_element.PRIORITY
     *
     * @param priority the value for ao_d5e466_element.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}