package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.AoD5e466WorkingDayPeriod;
import cn.topdeep.projgroup.entity.jiradb.AoD5e466WorkingDayPeriodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AoD5e466WorkingDayPeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int countByExample(AoD5e466WorkingDayPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int deleteByExample(AoD5e466WorkingDayPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int insert(AoD5e466WorkingDayPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int insertSelective(AoD5e466WorkingDayPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    List<AoD5e466WorkingDayPeriod> selectByExample(AoD5e466WorkingDayPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    AoD5e466WorkingDayPeriod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AoD5e466WorkingDayPeriod record, @Param("example") AoD5e466WorkingDayPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AoD5e466WorkingDayPeriod record, @Param("example") AoD5e466WorkingDayPeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AoD5e466WorkingDayPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_working_day_period
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AoD5e466WorkingDayPeriod record);
}