package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.AoD5e466CalendarYear;
import cn.topdeep.projgroup.entity.jiradb.AoD5e466CalendarYearExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AoD5e466CalendarYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int countByExample(AoD5e466CalendarYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int deleteByExample(AoD5e466CalendarYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int insert(AoD5e466CalendarYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int insertSelective(AoD5e466CalendarYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    List<AoD5e466CalendarYear> selectByExample(AoD5e466CalendarYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    AoD5e466CalendarYear selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AoD5e466CalendarYear record, @Param("example") AoD5e466CalendarYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AoD5e466CalendarYear record, @Param("example") AoD5e466CalendarYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AoD5e466CalendarYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_d5e466_calendar_year
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AoD5e466CalendarYear record);
}