package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.AoDc78d7HudsonAssociation;
import cn.topdeep.projgroup.entity.jiradb.AoDc78d7HudsonAssociationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AoDc78d7HudsonAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int countByExample(AoDc78d7HudsonAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int deleteByExample(AoDc78d7HudsonAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int insert(AoDc78d7HudsonAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int insertSelective(AoDc78d7HudsonAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    List<AoDc78d7HudsonAssociation> selectByExample(AoDc78d7HudsonAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    AoDc78d7HudsonAssociation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AoDc78d7HudsonAssociation record, @Param("example") AoDc78d7HudsonAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AoDc78d7HudsonAssociation record, @Param("example") AoDc78d7HudsonAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AoDc78d7HudsonAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ao_dc78d7_hudson_association
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AoDc78d7HudsonAssociation record);
}