package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Configurationcontext;
import cn.topdeep.projgroup.entity.jiradb.ConfigurationcontextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigurationcontextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int countByExample(ConfigurationcontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigurationcontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int insert(Configurationcontext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int insertSelective(Configurationcontext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    List<Configurationcontext> selectByExample(ConfigurationcontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    Configurationcontext selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Configurationcontext record, @Param("example") ConfigurationcontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Configurationcontext record, @Param("example") ConfigurationcontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Configurationcontext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configurationcontext
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Configurationcontext record);
}