package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;
import java.util.Date;

public class CwdApplication extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.application_name
     *
     * @mbggenerated
     */
    private String applicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.lower_application_name
     *
     * @mbggenerated
     */
    private String lowerApplicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.active
     *
     * @mbggenerated
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.application_type
     *
     * @mbggenerated
     */
    private String applicationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_application.credential
     *
     * @mbggenerated
     */
    private String credential;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_application
     *
     * @mbggenerated
     */
    public CwdApplication(Long id, String applicationName, String lowerApplicationName, Date createdDate, Date updatedDate, Integer active, String description, String applicationType, String credential) {
        this.id = id;
        this.applicationName = applicationName;
        this.lowerApplicationName = lowerApplicationName;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.active = active;
        this.description = description;
        this.applicationType = applicationType;
        this.credential = credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_application
     *
     * @mbggenerated
     */
    public CwdApplication() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.ID
     *
     * @return the value of cwd_application.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.ID
     *
     * @param id the value for cwd_application.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.application_name
     *
     * @return the value of cwd_application.application_name
     *
     * @mbggenerated
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.application_name
     *
     * @param applicationName the value for cwd_application.application_name
     *
     * @mbggenerated
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.lower_application_name
     *
     * @return the value of cwd_application.lower_application_name
     *
     * @mbggenerated
     */
    public String getLowerApplicationName() {
        return lowerApplicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.lower_application_name
     *
     * @param lowerApplicationName the value for cwd_application.lower_application_name
     *
     * @mbggenerated
     */
    public void setLowerApplicationName(String lowerApplicationName) {
        this.lowerApplicationName = lowerApplicationName == null ? null : lowerApplicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.created_date
     *
     * @return the value of cwd_application.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.created_date
     *
     * @param createdDate the value for cwd_application.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.updated_date
     *
     * @return the value of cwd_application.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.updated_date
     *
     * @param updatedDate the value for cwd_application.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.active
     *
     * @return the value of cwd_application.active
     *
     * @mbggenerated
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.active
     *
     * @param active the value for cwd_application.active
     *
     * @mbggenerated
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.description
     *
     * @return the value of cwd_application.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.description
     *
     * @param description the value for cwd_application.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.application_type
     *
     * @return the value of cwd_application.application_type
     *
     * @mbggenerated
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.application_type
     *
     * @param applicationType the value for cwd_application.application_type
     *
     * @mbggenerated
     */
    public void setApplicationType(String applicationType) {
        this.applicationType = applicationType == null ? null : applicationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_application.credential
     *
     * @return the value of cwd_application.credential
     *
     * @mbggenerated
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_application.credential
     *
     * @param credential the value for cwd_application.credential
     *
     * @mbggenerated
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }
}