package cn.topdeep.projgroup.entity.jiradb;

public class CwdDirectoryAttribute extends CwdDirectoryAttributeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_directory_attribute.attribute_value
     *
     * @mbggenerated
     */
    private String attributeValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    public CwdDirectoryAttribute(Long directoryId, String attributeName, String attributeValue) {
        super(directoryId, attributeName);
        this.attributeValue = attributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    public CwdDirectoryAttribute() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_directory_attribute.attribute_value
     *
     * @return the value of cwd_directory_attribute.attribute_value
     *
     * @mbggenerated
     */
    public String getAttributeValue() {
        return attributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_directory_attribute.attribute_value
     *
     * @param attributeValue the value for cwd_directory_attribute.attribute_value
     *
     * @mbggenerated
     */
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue == null ? null : attributeValue.trim();
    }
}