package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.CwdDirectory;
import cn.topdeep.projgroup.entity.jiradb.CwdDirectoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwdDirectoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int countByExample(CwdDirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int deleteByExample(CwdDirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int insert(CwdDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int insertSelective(CwdDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    List<CwdDirectory> selectByExample(CwdDirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    CwdDirectory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CwdDirectory record, @Param("example") CwdDirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CwdDirectory record, @Param("example") CwdDirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CwdDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CwdDirectory record);
}