package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.CwdDirectoryAttribute;
import cn.topdeep.projgroup.entity.jiradb.CwdDirectoryAttributeExample;
import cn.topdeep.projgroup.entity.jiradb.CwdDirectoryAttributeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwdDirectoryAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int countByExample(CwdDirectoryAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int deleteByExample(CwdDirectoryAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CwdDirectoryAttributeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int insert(CwdDirectoryAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int insertSelective(CwdDirectoryAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    List<CwdDirectoryAttribute> selectByExample(CwdDirectoryAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    CwdDirectoryAttribute selectByPrimaryKey(CwdDirectoryAttributeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CwdDirectoryAttribute record, @Param("example") CwdDirectoryAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CwdDirectoryAttribute record, @Param("example") CwdDirectoryAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CwdDirectoryAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_directory_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CwdDirectoryAttribute record);
}