package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.CwdGroupAttributes;
import cn.topdeep.projgroup.entity.jiradb.CwdGroupAttributesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwdGroupAttributesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int countByExample(CwdGroupAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int deleteByExample(CwdGroupAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int insert(CwdGroupAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int insertSelective(CwdGroupAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    List<CwdGroupAttributes> selectByExample(CwdGroupAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    CwdGroupAttributes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CwdGroupAttributes record, @Param("example") CwdGroupAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CwdGroupAttributes record, @Param("example") CwdGroupAttributesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CwdGroupAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_group_attributes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CwdGroupAttributes record);
}