package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;

public class CwdUserAttributes extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_user_attributes.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_user_attributes.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_user_attributes.directory_id
     *
     * @mbggenerated
     */
    private Long directoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_user_attributes.attribute_name
     *
     * @mbggenerated
     */
    private String attributeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_user_attributes.attribute_value
     *
     * @mbggenerated
     */
    private String attributeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwd_user_attributes.lower_attribute_value
     *
     * @mbggenerated
     */
    private String lowerAttributeValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_user_attributes
     *
     * @mbggenerated
     */
    public CwdUserAttributes(Long id, Long userId, Long directoryId, String attributeName, String attributeValue, String lowerAttributeValue) {
        this.id = id;
        this.userId = userId;
        this.directoryId = directoryId;
        this.attributeName = attributeName;
        this.attributeValue = attributeValue;
        this.lowerAttributeValue = lowerAttributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwd_user_attributes
     *
     * @mbggenerated
     */
    public CwdUserAttributes() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_user_attributes.ID
     *
     * @return the value of cwd_user_attributes.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_user_attributes.ID
     *
     * @param id the value for cwd_user_attributes.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_user_attributes.user_id
     *
     * @return the value of cwd_user_attributes.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_user_attributes.user_id
     *
     * @param userId the value for cwd_user_attributes.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_user_attributes.directory_id
     *
     * @return the value of cwd_user_attributes.directory_id
     *
     * @mbggenerated
     */
    public Long getDirectoryId() {
        return directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_user_attributes.directory_id
     *
     * @param directoryId the value for cwd_user_attributes.directory_id
     *
     * @mbggenerated
     */
    public void setDirectoryId(Long directoryId) {
        this.directoryId = directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_user_attributes.attribute_name
     *
     * @return the value of cwd_user_attributes.attribute_name
     *
     * @mbggenerated
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_user_attributes.attribute_name
     *
     * @param attributeName the value for cwd_user_attributes.attribute_name
     *
     * @mbggenerated
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName == null ? null : attributeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_user_attributes.attribute_value
     *
     * @return the value of cwd_user_attributes.attribute_value
     *
     * @mbggenerated
     */
    public String getAttributeValue() {
        return attributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_user_attributes.attribute_value
     *
     * @param attributeValue the value for cwd_user_attributes.attribute_value
     *
     * @mbggenerated
     */
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue == null ? null : attributeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwd_user_attributes.lower_attribute_value
     *
     * @return the value of cwd_user_attributes.lower_attribute_value
     *
     * @mbggenerated
     */
    public String getLowerAttributeValue() {
        return lowerAttributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwd_user_attributes.lower_attribute_value
     *
     * @param lowerAttributeValue the value for cwd_user_attributes.lower_attribute_value
     *
     * @mbggenerated
     */
    public void setLowerAttributeValue(String lowerAttributeValue) {
        this.lowerAttributeValue = lowerAttributeValue == null ? null : lowerAttributeValue.trim();
    }
}