package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Fieldconfigschemeissuetype;
import cn.topdeep.projgroup.entity.jiradb.FieldconfigschemeissuetypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldconfigschemeissuetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int countByExample(FieldconfigschemeissuetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int deleteByExample(FieldconfigschemeissuetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int insert(Fieldconfigschemeissuetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int insertSelective(Fieldconfigschemeissuetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    List<Fieldconfigschemeissuetype> selectByExample(FieldconfigschemeissuetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    Fieldconfigschemeissuetype selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fieldconfigschemeissuetype record, @Param("example") FieldconfigschemeissuetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fieldconfigschemeissuetype record, @Param("example") FieldconfigschemeissuetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fieldconfigschemeissuetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfigschemeissuetype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fieldconfigschemeissuetype record);
}