package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Fieldlayoutschemeassociation;
import cn.topdeep.projgroup.entity.jiradb.FieldlayoutschemeassociationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldlayoutschemeassociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int countByExample(FieldlayoutschemeassociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int deleteByExample(FieldlayoutschemeassociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int insert(Fieldlayoutschemeassociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int insertSelective(Fieldlayoutschemeassociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    List<Fieldlayoutschemeassociation> selectByExample(FieldlayoutschemeassociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    Fieldlayoutschemeassociation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fieldlayoutschemeassociation record, @Param("example") FieldlayoutschemeassociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fieldlayoutschemeassociation record, @Param("example") FieldlayoutschemeassociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fieldlayoutschemeassociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeassociation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fieldlayoutschemeassociation record);
}