package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Fieldlayoutschemeentity;
import cn.topdeep.projgroup.entity.jiradb.FieldlayoutschemeentityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldlayoutschemeentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int countByExample(FieldlayoutschemeentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int deleteByExample(FieldlayoutschemeentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int insert(Fieldlayoutschemeentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int insertSelective(Fieldlayoutschemeentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    List<Fieldlayoutschemeentity> selectByExample(FieldlayoutschemeentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    Fieldlayoutschemeentity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fieldlayoutschemeentity record, @Param("example") FieldlayoutschemeentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fieldlayoutschemeentity record, @Param("example") FieldlayoutschemeentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fieldlayoutschemeentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldlayoutschemeentity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fieldlayoutschemeentity record);
}