package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Fieldscreentab;
import cn.topdeep.projgroup.entity.jiradb.FieldscreentabExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldscreentabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int countByExample(FieldscreentabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int deleteByExample(FieldscreentabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int insert(Fieldscreentab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int insertSelective(Fieldscreentab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    List<Fieldscreentab> selectByExample(FieldscreentabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    Fieldscreentab selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fieldscreentab record, @Param("example") FieldscreentabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fieldscreentab record, @Param("example") FieldscreentabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fieldscreentab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldscreentab
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fieldscreentab record);
}