package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Fieldconfiguration;
import cn.topdeep.projgroup.entity.jiradb.FieldconfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldconfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int countByExample(FieldconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int deleteByExample(FieldconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int insert(Fieldconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int insertSelective(Fieldconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    List<Fieldconfiguration> selectByExampleWithBLOBs(FieldconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    List<Fieldconfiguration> selectByExample(FieldconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    Fieldconfiguration selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fieldconfiguration record, @Param("example") FieldconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Fieldconfiguration record, @Param("example") FieldconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fieldconfiguration record, @Param("example") FieldconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fieldconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Fieldconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fieldconfiguration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fieldconfiguration record);
}