package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Fileattachment;
import cn.topdeep.projgroup.entity.jiradb.FileattachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileattachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int countByExample(FileattachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int deleteByExample(FileattachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int insert(Fileattachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int insertSelective(Fileattachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    List<Fileattachment> selectByExample(FileattachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    Fileattachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fileattachment record, @Param("example") FileattachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fileattachment record, @Param("example") FileattachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fileattachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileattachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fileattachment record);
}