package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Filtersubscription;
import cn.topdeep.projgroup.entity.jiradb.FiltersubscriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FiltersubscriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int countByExample(FiltersubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int deleteByExample(FiltersubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int insert(Filtersubscription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int insertSelective(Filtersubscription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    List<Filtersubscription> selectByExample(FiltersubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    Filtersubscription selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Filtersubscription record, @Param("example") FiltersubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Filtersubscription record, @Param("example") FiltersubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Filtersubscription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filtersubscription
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Filtersubscription record);
}