package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Genericconfiguration;
import cn.topdeep.projgroup.entity.jiradb.GenericconfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GenericconfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int countByExample(GenericconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int deleteByExample(GenericconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int insert(Genericconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int insertSelective(Genericconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    List<Genericconfiguration> selectByExampleWithBLOBs(GenericconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    List<Genericconfiguration> selectByExample(GenericconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    Genericconfiguration selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Genericconfiguration record, @Param("example") GenericconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Genericconfiguration record, @Param("example") GenericconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Genericconfiguration record, @Param("example") GenericconfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Genericconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Genericconfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table genericconfiguration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Genericconfiguration record);
}