package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Issuelinktype;
import cn.topdeep.projgroup.entity.jiradb.IssuelinktypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssuelinktypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int countByExample(IssuelinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int deleteByExample(IssuelinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int insert(Issuelinktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int insertSelective(Issuelinktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    List<Issuelinktype> selectByExample(IssuelinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    Issuelinktype selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Issuelinktype record, @Param("example") IssuelinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Issuelinktype record, @Param("example") IssuelinktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Issuelinktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuelinktype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Issuelinktype record);
}