package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Issuesecurityscheme;
import cn.topdeep.projgroup.entity.jiradb.IssuesecurityschemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssuesecurityschemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int countByExample(IssuesecurityschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int deleteByExample(IssuesecurityschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int insert(Issuesecurityscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int insertSelective(Issuesecurityscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    List<Issuesecurityscheme> selectByExampleWithBLOBs(IssuesecurityschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    List<Issuesecurityscheme> selectByExample(IssuesecurityschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    Issuesecurityscheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Issuesecurityscheme record, @Param("example") IssuesecurityschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Issuesecurityscheme record, @Param("example") IssuesecurityschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Issuesecurityscheme record, @Param("example") IssuesecurityschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Issuesecurityscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Issuesecurityscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuesecurityscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Issuesecurityscheme record);
}