package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;

public class Issuetype extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issuetype.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issuetype.SEQUENCE
     *
     * @mbggenerated
     */
    private Long sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issuetype.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issuetype.pstyle
     *
     * @mbggenerated
     */
    private String pstyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issuetype.ICONURL
     *
     * @mbggenerated
     */
    private String iconurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issuetype.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetype
     *
     * @mbggenerated
     */
    public Issuetype(String id, Long sequence, String pname, String pstyle, String iconurl, String description) {
        this.id = id;
        this.sequence = sequence;
        this.pname = pname;
        this.pstyle = pstyle;
        this.iconurl = iconurl;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetype
     *
     * @mbggenerated
     */
    public Issuetype() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issuetype.ID
     *
     * @return the value of issuetype.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issuetype.ID
     *
     * @param id the value for issuetype.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issuetype.SEQUENCE
     *
     * @return the value of issuetype.SEQUENCE
     *
     * @mbggenerated
     */
    public Long getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issuetype.SEQUENCE
     *
     * @param sequence the value for issuetype.SEQUENCE
     *
     * @mbggenerated
     */
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issuetype.pname
     *
     * @return the value of issuetype.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issuetype.pname
     *
     * @param pname the value for issuetype.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issuetype.pstyle
     *
     * @return the value of issuetype.pstyle
     *
     * @mbggenerated
     */
    public String getPstyle() {
        return pstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issuetype.pstyle
     *
     * @param pstyle the value for issuetype.pstyle
     *
     * @mbggenerated
     */
    public void setPstyle(String pstyle) {
        this.pstyle = pstyle == null ? null : pstyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issuetype.ICONURL
     *
     * @return the value of issuetype.ICONURL
     *
     * @mbggenerated
     */
    public String getIconurl() {
        return iconurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issuetype.ICONURL
     *
     * @param iconurl the value for issuetype.ICONURL
     *
     * @mbggenerated
     */
    public void setIconurl(String iconurl) {
        this.iconurl = iconurl == null ? null : iconurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issuetype.DESCRIPTION
     *
     * @return the value of issuetype.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issuetype.DESCRIPTION
     *
     * @param description the value for issuetype.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}