package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Issuetypescreenscheme;
import cn.topdeep.projgroup.entity.jiradb.IssuetypescreenschemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssuetypescreenschemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int countByExample(IssuetypescreenschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int deleteByExample(IssuetypescreenschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int insert(Issuetypescreenscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int insertSelective(Issuetypescreenscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    List<Issuetypescreenscheme> selectByExample(IssuetypescreenschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    Issuetypescreenscheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Issuetypescreenscheme record, @Param("example") IssuetypescreenschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Issuetypescreenscheme record, @Param("example") IssuetypescreenschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Issuetypescreenscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issuetypescreenscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Issuetypescreenscheme record);
}