package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Jiradraftworkflows;
import cn.topdeep.projgroup.entity.jiradb.JiradraftworkflowsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JiradraftworkflowsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int countByExample(JiradraftworkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int deleteByExample(JiradraftworkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int insert(Jiradraftworkflows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int insertSelective(Jiradraftworkflows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    List<Jiradraftworkflows> selectByExampleWithBLOBs(JiradraftworkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    List<Jiradraftworkflows> selectByExample(JiradraftworkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    Jiradraftworkflows selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Jiradraftworkflows record, @Param("example") JiradraftworkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Jiradraftworkflows record, @Param("example") JiradraftworkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Jiradraftworkflows record, @Param("example") JiradraftworkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Jiradraftworkflows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Jiradraftworkflows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jiradraftworkflows
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Jiradraftworkflows record);
}