package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Notificationscheme;
import cn.topdeep.projgroup.entity.jiradb.NotificationschemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotificationschemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int countByExample(NotificationschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int deleteByExample(NotificationschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int insert(Notificationscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int insertSelective(Notificationscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    List<Notificationscheme> selectByExampleWithBLOBs(NotificationschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    List<Notificationscheme> selectByExample(NotificationschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    Notificationscheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Notificationscheme record, @Param("example") NotificationschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Notificationscheme record, @Param("example") NotificationschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Notificationscheme record, @Param("example") NotificationschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Notificationscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Notificationscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Notificationscheme record);
}