package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Oauthconsumer;
import cn.topdeep.projgroup.entity.jiradb.OauthconsumerExample;
import cn.topdeep.projgroup.entity.jiradb.OauthconsumerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthconsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int countByExample(OauthconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int deleteByExample(OauthconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int insert(OauthconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int insertSelective(OauthconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    List<OauthconsumerWithBLOBs> selectByExampleWithBLOBs(OauthconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    List<Oauthconsumer> selectByExample(OauthconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    OauthconsumerWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OauthconsumerWithBLOBs record, @Param("example") OauthconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OauthconsumerWithBLOBs record, @Param("example") OauthconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Oauthconsumer record, @Param("example") OauthconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OauthconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OauthconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthconsumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Oauthconsumer record);
}