package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Oauthspconsumer;
import cn.topdeep.projgroup.entity.jiradb.OauthspconsumerExample;
import cn.topdeep.projgroup.entity.jiradb.OauthspconsumerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthspconsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int countByExample(OauthspconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int deleteByExample(OauthspconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int insert(OauthspconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int insertSelective(OauthspconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    List<OauthspconsumerWithBLOBs> selectByExampleWithBLOBs(OauthspconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    List<Oauthspconsumer> selectByExample(OauthspconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    OauthspconsumerWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OauthspconsumerWithBLOBs record, @Param("example") OauthspconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OauthspconsumerWithBLOBs record, @Param("example") OauthspconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Oauthspconsumer record, @Param("example") OauthspconsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OauthspconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OauthspconsumerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauthspconsumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Oauthspconsumer record);
}