package cn.topdeep.projgroup.entity.jiradb;

import common.entity.Page;
import java.util.ArrayList;
import java.util.List;

public class OptionconfigurationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public OptionconfigurationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFieldidIsNull() {
            addCriterion("FIELDID is null");
            return (Criteria) this;
        }

        public Criteria andFieldidIsNotNull() {
            addCriterion("FIELDID is not null");
            return (Criteria) this;
        }

        public Criteria andFieldidEqualTo(String value) {
            addCriterion("FIELDID =", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotEqualTo(String value) {
            addCriterion("FIELDID <>", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidGreaterThan(String value) {
            addCriterion("FIELDID >", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidGreaterThanOrEqualTo(String value) {
            addCriterion("FIELDID >=", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidLessThan(String value) {
            addCriterion("FIELDID <", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidLessThanOrEqualTo(String value) {
            addCriterion("FIELDID <=", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidLike(String value) {
            addCriterion("FIELDID like", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotLike(String value) {
            addCriterion("FIELDID not like", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidIn(List<String> values) {
            addCriterion("FIELDID in", values, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotIn(List<String> values) {
            addCriterion("FIELDID not in", values, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidBetween(String value1, String value2) {
            addCriterion("FIELDID between", value1, value2, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotBetween(String value1, String value2) {
            addCriterion("FIELDID not between", value1, value2, "fieldid");
            return (Criteria) this;
        }

        public Criteria andOptionidIsNull() {
            addCriterion("OPTIONID is null");
            return (Criteria) this;
        }

        public Criteria andOptionidIsNotNull() {
            addCriterion("OPTIONID is not null");
            return (Criteria) this;
        }

        public Criteria andOptionidEqualTo(String value) {
            addCriterion("OPTIONID =", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidNotEqualTo(String value) {
            addCriterion("OPTIONID <>", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidGreaterThan(String value) {
            addCriterion("OPTIONID >", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidGreaterThanOrEqualTo(String value) {
            addCriterion("OPTIONID >=", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidLessThan(String value) {
            addCriterion("OPTIONID <", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidLessThanOrEqualTo(String value) {
            addCriterion("OPTIONID <=", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidLike(String value) {
            addCriterion("OPTIONID like", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidNotLike(String value) {
            addCriterion("OPTIONID not like", value, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidIn(List<String> values) {
            addCriterion("OPTIONID in", values, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidNotIn(List<String> values) {
            addCriterion("OPTIONID not in", values, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidBetween(String value1, String value2) {
            addCriterion("OPTIONID between", value1, value2, "optionid");
            return (Criteria) this;
        }

        public Criteria andOptionidNotBetween(String value1, String value2) {
            addCriterion("OPTIONID not between", value1, value2, "optionid");
            return (Criteria) this;
        }

        public Criteria andFieldconfigIsNull() {
            addCriterion("FIELDCONFIG is null");
            return (Criteria) this;
        }

        public Criteria andFieldconfigIsNotNull() {
            addCriterion("FIELDCONFIG is not null");
            return (Criteria) this;
        }

        public Criteria andFieldconfigEqualTo(Long value) {
            addCriterion("FIELDCONFIG =", value, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigNotEqualTo(Long value) {
            addCriterion("FIELDCONFIG <>", value, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigGreaterThan(Long value) {
            addCriterion("FIELDCONFIG >", value, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigGreaterThanOrEqualTo(Long value) {
            addCriterion("FIELDCONFIG >=", value, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigLessThan(Long value) {
            addCriterion("FIELDCONFIG <", value, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigLessThanOrEqualTo(Long value) {
            addCriterion("FIELDCONFIG <=", value, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigIn(List<Long> values) {
            addCriterion("FIELDCONFIG in", values, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigNotIn(List<Long> values) {
            addCriterion("FIELDCONFIG not in", values, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigBetween(Long value1, Long value2) {
            addCriterion("FIELDCONFIG between", value1, value2, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andFieldconfigNotBetween(Long value1, Long value2) {
            addCriterion("FIELDCONFIG not between", value1, value2, "fieldconfig");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("SEQUENCE is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("SEQUENCE is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceEqualTo(Long value) {
            addCriterion("SEQUENCE =", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotEqualTo(Long value) {
            addCriterion("SEQUENCE <>", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThan(Long value) {
            addCriterion("SEQUENCE >", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(Long value) {
            addCriterion("SEQUENCE >=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThan(Long value) {
            addCriterion("SEQUENCE <", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThanOrEqualTo(Long value) {
            addCriterion("SEQUENCE <=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceIn(List<Long> values) {
            addCriterion("SEQUENCE in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotIn(List<Long> values) {
            addCriterion("SEQUENCE not in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceBetween(Long value1, Long value2) {
            addCriterion("SEQUENCE between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotBetween(Long value1, Long value2) {
            addCriterion("SEQUENCE not between", value1, value2, "sequence");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table optionconfiguration
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table optionconfiguration
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}