package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.OsHistorystepPrevExample;
import cn.topdeep.projgroup.entity.jiradb.OsHistorystepPrevKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OsHistorystepPrevMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    int countByExample(OsHistorystepPrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    int deleteByExample(OsHistorystepPrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OsHistorystepPrevKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    int insert(OsHistorystepPrevKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    int insertSelective(OsHistorystepPrevKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    List<OsHistorystepPrevKey> selectByExample(OsHistorystepPrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OsHistorystepPrevKey record, @Param("example") OsHistorystepPrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_historystep_prev
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OsHistorystepPrevKey record, @Param("example") OsHistorystepPrevExample example);
}