package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Permissionscheme;
import cn.topdeep.projgroup.entity.jiradb.PermissionschemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionschemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int countByExample(PermissionschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int deleteByExample(PermissionschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int insert(Permissionscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int insertSelective(Permissionscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    List<Permissionscheme> selectByExampleWithBLOBs(PermissionschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    List<Permissionscheme> selectByExample(PermissionschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    Permissionscheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Permissionscheme record, @Param("example") PermissionschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Permissionscheme record, @Param("example") PermissionschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Permissionscheme record, @Param("example") PermissionschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Permissionscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Permissionscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Permissionscheme record);
}