package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;
import java.util.Date;

public class Pluginversion extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluginversion.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluginversion.pluginname
     *
     * @mbggenerated
     */
    private String pluginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluginversion.pluginkey
     *
     * @mbggenerated
     */
    private String pluginkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluginversion.pluginversion
     *
     * @mbggenerated
     */
    private String pluginversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluginversion.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pluginversion
     *
     * @mbggenerated
     */
    public Pluginversion(Long id, String pluginname, String pluginkey, String pluginversion, Date created) {
        this.id = id;
        this.pluginname = pluginname;
        this.pluginkey = pluginkey;
        this.pluginversion = pluginversion;
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pluginversion
     *
     * @mbggenerated
     */
    public Pluginversion() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluginversion.ID
     *
     * @return the value of pluginversion.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluginversion.ID
     *
     * @param id the value for pluginversion.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluginversion.pluginname
     *
     * @return the value of pluginversion.pluginname
     *
     * @mbggenerated
     */
    public String getPluginname() {
        return pluginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluginversion.pluginname
     *
     * @param pluginname the value for pluginversion.pluginname
     *
     * @mbggenerated
     */
    public void setPluginname(String pluginname) {
        this.pluginname = pluginname == null ? null : pluginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluginversion.pluginkey
     *
     * @return the value of pluginversion.pluginkey
     *
     * @mbggenerated
     */
    public String getPluginkey() {
        return pluginkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluginversion.pluginkey
     *
     * @param pluginkey the value for pluginversion.pluginkey
     *
     * @mbggenerated
     */
    public void setPluginkey(String pluginkey) {
        this.pluginkey = pluginkey == null ? null : pluginkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluginversion.pluginversion
     *
     * @return the value of pluginversion.pluginversion
     *
     * @mbggenerated
     */
    public String getPluginversion() {
        return pluginversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluginversion.pluginversion
     *
     * @param pluginversion the value for pluginversion.pluginversion
     *
     * @mbggenerated
     */
    public void setPluginversion(String pluginversion) {
        this.pluginversion = pluginversion == null ? null : pluginversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluginversion.CREATED
     *
     * @return the value of pluginversion.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluginversion.CREATED
     *
     * @param created the value for pluginversion.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}