package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;
import java.util.Date;

public class Projectversion extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.PROJECT
     *
     * @mbggenerated
     */
    private Long project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.vname
     *
     * @mbggenerated
     */
    private String vname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.SEQUENCE
     *
     * @mbggenerated
     */
    private Long sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.RELEASED
     *
     * @mbggenerated
     */
    private String released;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.ARCHIVED
     *
     * @mbggenerated
     */
    private String archived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.RELEASEDATE
     *
     * @mbggenerated
     */
    private Date releasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectversion.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectversion
     *
     * @mbggenerated
     */
    public Projectversion(Long id, Long project, String vname, Long sequence, String released, String archived, String url, Date releasedate, String description) {
        this.id = id;
        this.project = project;
        this.vname = vname;
        this.sequence = sequence;
        this.released = released;
        this.archived = archived;
        this.url = url;
        this.releasedate = releasedate;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectversion
     *
     * @mbggenerated
     */
    public Projectversion() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.ID
     *
     * @return the value of projectversion.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.ID
     *
     * @param id the value for projectversion.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.PROJECT
     *
     * @return the value of projectversion.PROJECT
     *
     * @mbggenerated
     */
    public Long getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.PROJECT
     *
     * @param project the value for projectversion.PROJECT
     *
     * @mbggenerated
     */
    public void setProject(Long project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.vname
     *
     * @return the value of projectversion.vname
     *
     * @mbggenerated
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.vname
     *
     * @param vname the value for projectversion.vname
     *
     * @mbggenerated
     */
    public void setVname(String vname) {
        this.vname = vname == null ? null : vname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.SEQUENCE
     *
     * @return the value of projectversion.SEQUENCE
     *
     * @mbggenerated
     */
    public Long getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.SEQUENCE
     *
     * @param sequence the value for projectversion.SEQUENCE
     *
     * @mbggenerated
     */
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.RELEASED
     *
     * @return the value of projectversion.RELEASED
     *
     * @mbggenerated
     */
    public String getReleased() {
        return released;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.RELEASED
     *
     * @param released the value for projectversion.RELEASED
     *
     * @mbggenerated
     */
    public void setReleased(String released) {
        this.released = released == null ? null : released.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.ARCHIVED
     *
     * @return the value of projectversion.ARCHIVED
     *
     * @mbggenerated
     */
    public String getArchived() {
        return archived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.ARCHIVED
     *
     * @param archived the value for projectversion.ARCHIVED
     *
     * @mbggenerated
     */
    public void setArchived(String archived) {
        this.archived = archived == null ? null : archived.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.URL
     *
     * @return the value of projectversion.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.URL
     *
     * @param url the value for projectversion.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.RELEASEDATE
     *
     * @return the value of projectversion.RELEASEDATE
     *
     * @mbggenerated
     */
    public Date getReleasedate() {
        return releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.RELEASEDATE
     *
     * @param releasedate the value for projectversion.RELEASEDATE
     *
     * @mbggenerated
     */
    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectversion.DESCRIPTION
     *
     * @return the value of projectversion.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectversion.DESCRIPTION
     *
     * @param description the value for projectversion.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}