package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Propertydecimal;
import cn.topdeep.projgroup.entity.jiradb.PropertydecimalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertydecimalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int countByExample(PropertydecimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int deleteByExample(PropertydecimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int insert(Propertydecimal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int insertSelective(Propertydecimal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    List<Propertydecimal> selectByExample(PropertydecimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    Propertydecimal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Propertydecimal record, @Param("example") PropertydecimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Propertydecimal record, @Param("example") PropertydecimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Propertydecimal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydecimal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Propertydecimal record);
}