package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Propertyentry;
import cn.topdeep.projgroup.entity.jiradb.PropertyentryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertyentryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int countByExample(PropertyentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int deleteByExample(PropertyentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int insert(Propertyentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int insertSelective(Propertyentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    List<Propertyentry> selectByExample(PropertyentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    Propertyentry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Propertyentry record, @Param("example") PropertyentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Propertyentry record, @Param("example") PropertyentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Propertyentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyentry
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Propertyentry record);
}