package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Propertynumber;
import cn.topdeep.projgroup.entity.jiradb.PropertynumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertynumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int countByExample(PropertynumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int deleteByExample(PropertynumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int insert(Propertynumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int insertSelective(Propertynumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    List<Propertynumber> selectByExample(PropertynumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    Propertynumber selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Propertynumber record, @Param("example") PropertynumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Propertynumber record, @Param("example") PropertynumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Propertynumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertynumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Propertynumber record);
}