package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Propertystring;
import cn.topdeep.projgroup.entity.jiradb.PropertystringExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertystringMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int countByExample(PropertystringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int deleteByExample(PropertystringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int insert(Propertystring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int insertSelective(Propertystring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    List<Propertystring> selectByExampleWithBLOBs(PropertystringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    List<Propertystring> selectByExample(PropertystringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    Propertystring selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Propertystring record, @Param("example") PropertystringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Propertystring record, @Param("example") PropertystringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Propertystring record, @Param("example") PropertystringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Propertystring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertystring
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Propertystring record);
}