package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Propertydata;
import cn.topdeep.projgroup.entity.jiradb.PropertydataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertydataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int countByExample(PropertydataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int deleteByExample(PropertydataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int insert(Propertydata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int insertSelective(Propertydata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    List<Propertydata> selectByExampleWithBLOBs(PropertydataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    List<Propertydata> selectByExample(PropertydataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    Propertydata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Propertydata record, @Param("example") PropertydataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Propertydata record, @Param("example") PropertydataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Propertydata record, @Param("example") PropertydataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Propertydata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertydata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Propertydata record);
}