package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Remembermetoken;
import cn.topdeep.projgroup.entity.jiradb.RemembermetokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemembermetokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int countByExample(RemembermetokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int deleteByExample(RemembermetokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int insert(Remembermetoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int insertSelective(Remembermetoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    List<Remembermetoken> selectByExample(RemembermetokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    Remembermetoken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Remembermetoken record, @Param("example") RemembermetokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Remembermetoken record, @Param("example") RemembermetokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Remembermetoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remembermetoken
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Remembermetoken record);
}