package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Remotelink;
import cn.topdeep.projgroup.entity.jiradb.RemotelinkExample;
import cn.topdeep.projgroup.entity.jiradb.RemotelinkWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemotelinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int countByExample(RemotelinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int deleteByExample(RemotelinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int insert(RemotelinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int insertSelective(RemotelinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    List<RemotelinkWithBLOBs> selectByExampleWithBLOBs(RemotelinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    List<Remotelink> selectByExample(RemotelinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    RemotelinkWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RemotelinkWithBLOBs record, @Param("example") RemotelinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") RemotelinkWithBLOBs record, @Param("example") RemotelinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Remotelink record, @Param("example") RemotelinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RemotelinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RemotelinkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotelink
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Remotelink record);
}