package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Schemepermissions;
import cn.topdeep.projgroup.entity.jiradb.SchemepermissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemepermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int countByExample(SchemepermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int deleteByExample(SchemepermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int insert(Schemepermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int insertSelective(Schemepermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    List<Schemepermissions> selectByExample(SchemepermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    Schemepermissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Schemepermissions record, @Param("example") SchemepermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Schemepermissions record, @Param("example") SchemepermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Schemepermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schemepermissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Schemepermissions record);
}