package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.TrackbackPing;
import cn.topdeep.projgroup.entity.jiradb.TrackbackPingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrackbackPingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int countByExample(TrackbackPingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int deleteByExample(TrackbackPingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int insert(TrackbackPing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int insertSelective(TrackbackPing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    List<TrackbackPing> selectByExample(TrackbackPingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    TrackbackPing selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TrackbackPing record, @Param("example") TrackbackPingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TrackbackPing record, @Param("example") TrackbackPingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TrackbackPing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackback_ping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TrackbackPing record);
}