package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;

public class Upgradehistory extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upgradehistory.UPGRADECLASS
     *
     * @mbggenerated
     */
    private String upgradeclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upgradehistory.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upgradehistory.TARGETBUILD
     *
     * @mbggenerated
     */
    private String targetbuild;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    public Upgradehistory(String upgradeclass, Long id, String targetbuild) {
        this.upgradeclass = upgradeclass;
        this.id = id;
        this.targetbuild = targetbuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    public Upgradehistory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upgradehistory.UPGRADECLASS
     *
     * @return the value of upgradehistory.UPGRADECLASS
     *
     * @mbggenerated
     */
    public String getUpgradeclass() {
        return upgradeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upgradehistory.UPGRADECLASS
     *
     * @param upgradeclass the value for upgradehistory.UPGRADECLASS
     *
     * @mbggenerated
     */
    public void setUpgradeclass(String upgradeclass) {
        this.upgradeclass = upgradeclass == null ? null : upgradeclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upgradehistory.ID
     *
     * @return the value of upgradehistory.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upgradehistory.ID
     *
     * @param id the value for upgradehistory.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upgradehistory.TARGETBUILD
     *
     * @return the value of upgradehistory.TARGETBUILD
     *
     * @mbggenerated
     */
    public String getTargetbuild() {
        return targetbuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upgradehistory.TARGETBUILD
     *
     * @param targetbuild the value for upgradehistory.TARGETBUILD
     *
     * @mbggenerated
     */
    public void setTargetbuild(String targetbuild) {
        this.targetbuild = targetbuild == null ? null : targetbuild.trim();
    }
}