package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Upgradehistory;
import cn.topdeep.projgroup.entity.jiradb.UpgradehistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpgradehistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int countByExample(UpgradehistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int deleteByExample(UpgradehistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String upgradeclass);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int insert(Upgradehistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int insertSelective(Upgradehistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    List<Upgradehistory> selectByExample(UpgradehistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    Upgradehistory selectByPrimaryKey(String upgradeclass);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Upgradehistory record, @Param("example") UpgradehistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Upgradehistory record, @Param("example") UpgradehistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Upgradehistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upgradehistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Upgradehistory record);
}