package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Versioncontrol;
import cn.topdeep.projgroup.entity.jiradb.VersioncontrolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VersioncontrolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int countByExample(VersioncontrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int deleteByExample(VersioncontrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int insert(Versioncontrol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int insertSelective(Versioncontrol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    List<Versioncontrol> selectByExample(VersioncontrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    Versioncontrol selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Versioncontrol record, @Param("example") VersioncontrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Versioncontrol record, @Param("example") VersioncontrolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Versioncontrol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table versioncontrol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Versioncontrol record);
}