package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.base.BaseEntity;
import java.util.Date;

public class Votehistory extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votehistory.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votehistory.issueid
     *
     * @mbggenerated
     */
    private Long issueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votehistory.VOTES
     *
     * @mbggenerated
     */
    private Long votes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votehistory.TIMESTAMP
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votehistory
     *
     * @mbggenerated
     */
    public Votehistory(Long id, Long issueid, Long votes, Date timestamp) {
        this.id = id;
        this.issueid = issueid;
        this.votes = votes;
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votehistory
     *
     * @mbggenerated
     */
    public Votehistory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votehistory.ID
     *
     * @return the value of votehistory.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votehistory.ID
     *
     * @param id the value for votehistory.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votehistory.issueid
     *
     * @return the value of votehistory.issueid
     *
     * @mbggenerated
     */
    public Long getIssueid() {
        return issueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votehistory.issueid
     *
     * @param issueid the value for votehistory.issueid
     *
     * @mbggenerated
     */
    public void setIssueid(Long issueid) {
        this.issueid = issueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votehistory.VOTES
     *
     * @return the value of votehistory.VOTES
     *
     * @mbggenerated
     */
    public Long getVotes() {
        return votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votehistory.VOTES
     *
     * @param votes the value for votehistory.VOTES
     *
     * @mbggenerated
     */
    public void setVotes(Long votes) {
        this.votes = votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votehistory.TIMESTAMP
     *
     * @return the value of votehistory.TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votehistory.TIMESTAMP
     *
     * @param timestamp the value for votehistory.TIMESTAMP
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}