package cn.topdeep.projgroup.entity.jiradb;

import cn.topdeep.projgroup.entity.jiradb.Workflowscheme;
import cn.topdeep.projgroup.entity.jiradb.WorkflowschemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkflowschemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int countByExample(WorkflowschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int deleteByExample(WorkflowschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int insert(Workflowscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int insertSelective(Workflowscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    List<Workflowscheme> selectByExampleWithBLOBs(WorkflowschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    List<Workflowscheme> selectByExample(WorkflowschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    Workflowscheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Workflowscheme record, @Param("example") WorkflowschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Workflowscheme record, @Param("example") WorkflowschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Workflowscheme record, @Param("example") WorkflowschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Workflowscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Workflowscheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowscheme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Workflowscheme record);
}